# Generated by Django 4.2 on 2023-05-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='response_message',
            field=models.TextField(default=''),
        ),
    ]
